# Data
data_name = 'ml-100k' # ('ml-1m', 'ml-2k', 'ml-100k')
neighbor_num = 20

# Model
model_name = 'lgcn' # ('mf', 'emf', 'lgcn', 'egcn')
sample_method = 'explainable' # ('random', 'similarity', 'explainable')

# Train
epoch_num = 100
batch_size = 512

# Test
topk = 10
test_interval = 10

[mf]
latent_dim = 64
lr = 1e-3
weight_decay = 1e-4

[lgcn]
latent_dim = 64
layer_num = 3
lr = 1e-3
weight_decay = 1e-4

[emf]
latent_dim = 64
lr = 1e-3
weight_decay = 1e-4

[egcn]
latent_dim = 64
layer_num = 3
lr = 1e-3
weight_decay = 1e-4

